# Generated by Django 6.0.6 on 2026-06-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('vendedor', 'Vendedor'), ('gerente', 'Gerente')], default='vendedor', max_length=20),
        ),
    ]
