# Generated by Django 6.0.6 on 2026-08-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_roles_admin_gerente_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Al ingresar, se le va a exigir que elija una contraseña nueva.', verbose_name='debe cambiar la contraseña'),
        ),
    ]
