# Generated by Django 6.0.6 on 2026-08-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('gerente', 'Gerente'), ('empleado', 'Empleado'), ('tesoreria', 'Tesorería')], default='empleado', max_length=20, verbose_name='rol'),
        ),
    ]
