# Generated by Django 6.0.6 on 2026-08-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('gerente', 'Gerente'), ('empleado', 'Empleado'), ('tesoreria', 'Tesorería'), ('coach', 'Coach de ventas')], default='empleado', max_length=20, verbose_name='rol'),
        ),
    ]
