# Generated by Django 6.0.6 on 2026-06-08 15:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('productos', models.CharField(max_length=300)),
                ('cantidad', models.CharField(blank=True, max_length=50)),
                ('numero_cotizacion', models.CharField(blank=True, max_length=20)),
                ('via_entrada', models.CharField(choices=[('mail', 'Mail'), ('whatsapp', 'WhatsApp'), ('telefono', 'Teléfono'), ('recupero', 'Recuperé contacto')], default='whatsapp', max_length=20)),
                ('razon_social', models.CharField(blank=True, max_length=200)),
                ('contacto', models.CharField(blank=True, max_length=150)),
                ('cuit', models.CharField(blank=True, max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('estado', models.CharField(choices=[('cotizado', 'Cotizado'), ('facturado', 'Facturado'), ('compro_otro', 'Compró en otro lado'), ('no_compra', 'No va a comprar'), ('cancelado', 'Cancelado'), ('recontactar', 'Recontactar más adelante')], default='cotizado', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('fecha_seguimiento', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'consulta',
                'verbose_name_plural': 'consultas',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='consultas.consulta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
