# Generated by Django 6.0.6 on 2026-06-09 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='consultas.consulta')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='productos.producto')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
