# Generated by Django 6.0.6 on 2026-08-05 17:16

import django.db.models.deletion
from django.db import migrations, models


def heredar_cliente_de_la_consulta(apps, schema_editor):
    """Los seguimientos que ya existían pasan a la línea de tiempo de su cliente.

    Con Subquery y no con F('consulta__cliente'): un UPDATE no admite
    referencias a campos con join.
    """
    SeguimientoLog = apps.get_model('consultas', 'SeguimientoLog')
    Consulta = apps.get_model('consultas', 'Consulta')
    SeguimientoLog.objects.filter(cliente__isnull=True, consulta__isnull=False).update(
        cliente=models.Subquery(
            Consulta.objects.filter(pk=models.OuterRef('consulta_id')).values('cliente_id')[:1]
        )
    )


def revertir(apps, schema_editor):
    # El campo se elimina en el rollback del AddField; no hay nada que deshacer.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_vendedor'),
        ('consultas', '0004_populate_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientolog',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='seguimientolog',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='consultas.consulta'),
        ),
        migrations.RunPython(heredar_cliente_de_la_consulta, revertir),
    ]
