# Generated by Django 6.0.6 on 2026-08-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0005_seguimientolog_cliente_alter_seguimientolog_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='moneda',
            field=models.CharField(choices=[('ARS', 'Pesos'), ('USD', 'Dólares')], default='ARS', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='tipo_cambio',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Pesos por dólar. Solo hace falta si la cotización mezcla monedas.', max_digits=12, null=True, verbose_name='Tipo de cambio'),
        ),
        migrations.AddField(
            model_name='lineacotizacion',
            name='moneda',
            field=models.CharField(choices=[('ARS', 'Pesos'), ('USD', 'Dólares')], default='ARS', max_length=3, verbose_name='Moneda'),
        ),
    ]
