# Generated by Django 6.0.6 on 2026-09-09 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0006_consulta_moneda_consulta_tipo_cambio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionGenerada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='Nº de cotización')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total_neto', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('moneda', models.CharField(choices=[('ARS', 'Pesos'), ('USD', 'Dólares')], default='ARS', max_length=3)),
                ('enviada_at', models.DateTimeField(blank=True, null=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='consultas.consulta')),
                ('enviada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('generada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_generadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cotización generada',
                'verbose_name_plural': 'cotizaciones generadas',
                'ordering': ['-fecha'],
            },
        ),
    ]
