# Generated by Django 6.0.6 on 2026-09-15 13:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0007_cotizaciongenerada'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='alicuota_iva',
            field=models.DecimalField(choices=[(Decimal('21'), '21%'), (Decimal('10.5'), '10,5%'), (Decimal('0'), 'Exento (sin IVA)')], decimal_places=2, default=Decimal('21'), max_digits=4, verbose_name='IVA'),
        ),
    ]
