# Generated by Django 6.0.6 on 2026-06-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre')),
                ('categoria', models.CharField(blank=True, max_length=150, verbose_name='Categoría')),
                ('subcategoria', models.CharField(blank=True, max_length=150, verbose_name='Subcategoría')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Precio de venta')),
                ('activo', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['categoria', 'nombre'],
            },
        ),
    ]
