# Generated by Django 6.0.6 on 2026-06-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='especificaciones',
            field=models.TextField(blank=True, help_text='Bullet points separados por salto de línea', verbose_name='Especificaciones técnicas'),
        ),
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='foto_tipo',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
