# Generated by Django 6.0.6 on 2026-08-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_especificaciones_producto_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(blank=True, choices=[('UN', 'Unidad'), ('PAR', 'Par'), ('CAJA', 'Caja'), ('PACK', 'Pack'), ('BOLSA', 'Bolsa'), ('ROLLO', 'Rollo'), ('KG', 'Kilogramo'), ('GR', 'Gramo'), ('TN', 'Tonelada'), ('LT', 'Litro'), ('M', 'Metro'), ('M2', 'Metro cuadrado'), ('M3', 'Metro cúbico')], max_length=10, verbose_name='Unidad de medida'),
        ),
    ]
