# Generated by Django 6.0.6 on 2026-08-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='colores',
            field=models.CharField(blank=True, help_text='Sale en la cotización como "Colores: …". Vacío, no se imprime.', max_length=100, verbose_name='Colores'),
        ),
    ]
