# Generated by Django 6.0.6 on 2026-08-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código postal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='condicion_fiscal',
            field=models.CharField(blank=True, choices=[('Responsable Inscripto', 'Responsable Inscripto'), ('Responsable Monotributo', 'Responsable Monotributo'), ('Exento', 'Exento'), ('Consumidor final', 'Consumidor final'), ('No Categorizado', 'No Categorizado')], max_length=30, verbose_name='Condición fiscal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='dni',
            field=models.CharField(blank=True, max_length=15, verbose_name='DNI'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='domicilio',
            field=models.CharField(blank=True, max_length=200, verbose_name='Domicilio'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_facturacion',
            field=models.PositiveIntegerField(blank=True, help_text='Número de cliente en el sistema de facturación. Permite re-sincronizar la lista.', null=True, unique=True, verbose_name='ID en facturación'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia',
            field=models.CharField(blank=True, max_length=60, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_factura',
            field=models.CharField(blank=True, choices=[('Factura A', 'Factura A'), ('Factura B', 'Factura B'), ('Remito X', 'Remito X'), ('Sin especificar', 'Sin especificar')], max_length=20, verbose_name='Tipo de factura'),
        ),
    ]
